name: Experiment
on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
    - uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: v1.1.3
    - name: Cheking terraform version
      run: |
         terraform version
        

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest

    steps:
       - name: Hello world action
         env: # Set the secret as an input
           super_secret: ${{ secrets.TEST_ENV }}
         run: |
            echo "$super_secret"
       - name: Dependant is Running
         run: |
            echo "Completed job 2, but triggering failure"
        
