name: Experiment
on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Hello world action
      run: |
        ls 
        pwd
        echo "hi"
    - uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: v1.1.3
    - name: aws access
      env: # Set the secret as an input
           accsess_secret: ${{ secrets.ACCESS_KEY }}
      run: |
         ls -al
         ls
         pwd
         echo "is there anything ?"
    - name: aws secret
      env: # set secret
           secret_secret: ${{ secrets.SECRET_KEY }}
      run: |     
    - name: export aws cred
      run: |
         export AWS_ACCESS_KEY_ID=$accsess_secret
         export AWS_SECRET_ACCESS_KEY=$secret_secret
    - name: Doing terraform init
      run: |
         ls
         terraform init
         terraform plan
         terraform version
        

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest

    steps:
       - name: Hello world action
         run: |
            ls 
            pwd
       
