name: Experiment
on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v3
    - name: Hello world action
      run: |
        ls 
        pwd
        echo "hi"
    - name: "Setup - Build AWS Credentials"
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        cd ~/.aws
        ls
        cat credentials
    - uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: v1.1.3
    - name: Tar files
      run: | 
         tar -cvf whole_repo.tar /home/runner/work/actions-test/actions-test
         ls
         pwd
    - uses: actions/upload-artifact@v3
      with:
        name: from_job_one
        path: whole_repo.tar
        
  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest

    steps:
       - uses: actions/download-artifact@v3
         with:
           name: from_job_one
       - name: Hello world action
         run: |
            ls 
            pwd
