name: Experiment
on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
    - uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.1.7
    - name: Sleep and Run
      run: |
         terrform verion
        

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Dependant is Running
      run: |
        terraform version
        
