name: Experiment
on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Hello world action
      run: |
        ls 
        pwd
        echo "hi"
    - name: "Setup - Build AWS Credentials"
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        cd .aws
        ls
        cat credentials
    - uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: v1.1.3
    - name: Doing terraform init
      run: |
         ls
         terraform init
         terraform plan
         terraform version
        
  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest

    steps:
       - name: Hello world action
         run: |
            ls 
            pwd
