name: Experiment
on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Hello world action
      run: |
        ls 
        pwd
        echo "hi"
    - name: configure aws
    - shell: bash
      env:
         accsess_secret: ${{ secrets.ACCESS_KEY }}
         secret_secret: ${{ secrets.SECRET_KEY }}
      run: |
        export AWS_ACCESS_KEY_ID="$accsess_secret" 
        export AWS_SECRET_ACCESS_KEY="$secret_secret"  
    - uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: v1.1.3
    - name: Doing terraform init
      run: |
         ls
         terraform init
         terraform plan
         terraform version
        

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest

    steps:
       - name: Hello world action
         run: |
            ls 
            pwd
       
